name: Jekyll site CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
      - uses: actions/checkout@v1
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && chmod 777 /srv/jekyll/Gemfile.lock && jekyll build --future"